import os 

KAGGLE_FRAGMENTS_PATH = '../../input/vesuvius-challenge-ink-detection/train'
COOKIECUTTER_FRAGMENTS_PATH = 'data/raw/train'
FRAGMENTS_PATH =  COOKIECUTTER_FRAGMENTS_PATH if os.path.exists(COOKIECUTTER_FRAGMENTS_PATH) else KAGGLE_FRAGMENTS_PATH

KAGGLE_MODELS_PATH = '../../working/'
COOKIECUTTER_MODELS_PATH = 'models/'
MODELS_PATH = COOKIECUTTER_MODELS_PATH if os.path.exists(COOKIECUTTER_MODELS_PATH) else KAGGLE_MODELS_PATH
TRAIN_FRAGMENTS = ['1']
VAL_FRAGMENTS = ['3']

Z_START = 27
Z_DIM = 8
TILE_SIZE = 256