name: vesuvius-challenge-ink-detection-env
dependencies:
  - python=3.8.*
  - pip
  - conda-forge::opencv
  - fastai::opencv-python-headless
  - conda-forge::matplotlib
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - conda-forge::scikit-learn
  - conda-forge::wandb
  - pip:
    - pytorch-lightning # Numpy error using conda
    - torchgeometry
    - jupyter